'use strict'

module.exports = {
  USER: {
      URL_ERROR: '访问路径不正确',
      NEW_USER: '新用户',
      NOT_SIGNUP: '尚未注册',
      ACTIVE_EMAIL: '邮箱已激活',
      UNACTIVE: '尚未激活',
      USER_NOT_EXIST: '该用户不存在',
      USERNAME_EXIST: '该用户名已存在',
      EMAIL_EXIST: '该邮箱已被注册',
      CODE_ERROR: '验证码错误',
      SMS_ERROR: '短信发送频率过快, 请过几分钟再尝试',
      PWD_ERROR: '密码错误',
      SEND_MAIL_SUCCESS: '发送邮件成功',
      MAIL_CREAT_USER: '通过发送邮件创建新用户',
      MAIL_INSERT_PHONENUMBER: '合并手机用户的信息到邮箱账户的表单',
      PHONE_EXIST: '邮箱未验证,手机用户存在,发送短信',
      CREAT_PHONEUSER: '邮箱未验证，手机用户不存在,创建新的手机用户',
      PHONE_MAIL_EXIST: '该邮箱的验证用户已经存在',
      MAIL_PHONE_EXIST: '该手机的验证用户已经存在',
      VERIFIED: '已认证',
      LOGINED: '用户已登录',
      EMAIL_IS_REQUIRED: '邮箱不能为空',
      PHONE_IS_REQUIRED: '手机不能为空',
      USER_MAIL_EXIST: '该用户邮箱已存在',
      USER_PHONE_EXIST: '该手机号码已存在',
      PHONE_NOT_REGISTERED: '该手机号码尚未注册',
      PHONE_NOT_VERIFYED: '该手机号码尚未认证',
      MAIL_NOT_REGISTERED: '该邮箱尚未注册',
      REGISTERED_NOT_COMPLETELY: '改用户尚未注册完整',
      LOGIN_DISABLED: '由于尝试不正确的密码多次登录，您的帐户已被暂时禁用，请联系 Arpt 客服',
      THIRD_USER: '该用户是第三方注册用户',
      GET_CODE_FIRST: '得先获取验证码',
      TWO_PWD_UNMATCH: '两次输入的密码不一致',
      PWD_NOT_COMPARE: '旧的密码输入错误',
      USER_NOT_LOGINED: '用户没有登录',
      LINK_EXPIRED: '该链接已过期',
      DELETE_SUCCESS: '删除成功',
      DELETE_LOSE:'删除失败',
      ADD_SUCCESS:'添加成功',
      FIND_SUCCESS:'查找成功',
      PROJECT_EXIT:'该项目已存在，请删除后重新编辑',
      NOT_FOUND_USER: '查找用户失败'},
  COMMON: {
    DATA_EMPTY: '数据不能为空'
  }
}
